# Site settings
title: John Thompson
header-img: img/home-bg.jpg
description: "John Thompson's journalism portfolio. Yukon News editor. Cool stories from northern Canada."
baseurl: ""
url: "johngthompson.github.io"
# twitter_username: jayjeetee
# linkedin_username: johngthompson
excerpt_separator: "<!-- BREAK -->"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:categories/:title
paginate: 50
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
